export const gpsLsit = [
  {
    location: '종로구',
    latitude: 37.59708565258199,
    longitude: 126.97061972318878,
  },
  {
    location: '중구',
    latitude: 37.560190897864906,
    longitude: 126.99759845710656,
  },
  {
    location: '용산구',
    latitude: 37.53316613137628,
    longitude: 126.98160092274547,
  },
  {
    location: '성동구',
    latitude: 37.55438802700418,
    longitude: 127.04261109326114,
  },
  {
    location: '광진구',
    latitude: 37.54795065120619,
    longitude: 127.08618628445537,
  },
  {
    location: '동대문구',
    latitude: 37.58201488151701,
    longitude: 127.05536694729514,
  },
  {
    location: '중랑구',
    latitude: 37.59782740643261,
    longitude: 127.0924422334882,
  },
  {
    location: '성북구',
    latitude: 37.60076412577266,
    longitude: 127.02025770037797,
  },
  {
    location: '강북구',
    latitude: 37.64372246698335,
    longitude: 127.01074149785245,
  },
  {
    location: '도봉구',
    latitude: 37.66935264903244,
    longitude: 127.03313358882534,
  },
  {
    location: '노원구',
    latitude: 37.653239123910296,
    longitude: 127.07542382059665,
  },
  {
    location: '은평구',
    latitude: 37.61913714094425,
    longitude: 126.92646102493488,
  },
  {
    location: '서대문구',
    latitude: 37.57671367464311,
    longitude: 126.93943995057974,
  },
  {
    location: '마포구',
    latitude: 37.560760023757126,
    longitude: 126.90811246733483,
  },
  {
    location: '양천구',
    latitude: 37.521073264355316,
    longitude: 126.85867787691797,
  },
  {
    location: '강서구',
    latitude: 37.56129666464895,
    longitude: 126.82890328601613,
  },
  {
    location: '구로구',
    latitude: 37.496652116049916,
    longitude: 126.85556388383493,
  },
  {
    location: '금천구',
    latitude: 37.46106931550623,
    longitude: 126.90218472919369,
  },
  {
    location: '영등포구',
    latitude: 37.51826061974146,
    longitude: 126.90983811339568,
  },
  {
    location: '동작구',
    latitude: 37.502349069229005,
    longitude: 126.9540453463608,
  },
  {
    location: '관악구',
    latitude: 37.46857041258146,
    longitude: 126.94599988124855,
  },
  {
    location: '서초구',
    latitude: 37.47094980878414,
    longitude: 127.03231696067189,
  },
  {
    location: '강남구',
    latitude: 37.493950336362744,
    longitude: 127.06261741977121,
  },
  {
    location: '송파구',
    latitude: 37.50401757964911,
    longitude: 127.12045074883561,
  },
  {
    location: '강동구',
    latitude: 37.551317449147675,
    longitude: 127.14797672715729,
  },
];

export const bigGpsList = [
  '서울특별시',
  '부산광역시',
  '대구광역시',
  '인천광역시',
  '광주광역시',
  '대전광역시',
  '울산광역시',
  '세종특별자치시',
  '경기도',
  '강원도',
  '충청북도',
  '충청남도',
  '전라북도',
  '전라남도',
  '경상북도',
  '경상남도',
  '제주특별자치도',
];

export const smallGpsList = [
  { name: '서울특별시', gps: '종로구' },
  { name: '서울특별시', gps: '중구' },
  { name: '서울특별시', gps: '용산구' },
  { name: '서울특별시', gps: '성동구' },
  { name: '서울특별시', gps: '광진구' },
  { name: '서울특별시', gps: '동대문구' },
  { name: '서울특별시', gps: '중랑구' },
  { name: '서울특별시', gps: '성북구' },
  { name: '서울특별시', gps: '강북구' },
  { name: '서울특별시', gps: '도봉구' },
  { name: '서울특별시', gps: '노원구' },
  { name: '서울특별시', gps: '은평구' },
  { name: '서울특별시', gps: '서대문구' },
  { name: '서울특별시', gps: '마포구' },
  { name: '서울특별시', gps: '양천구' },
  { name: '서울특별시', gps: '강서구' },
  { name: '서울특별시', gps: '구로구' },
  { name: '서울특별시', gps: '금천구' },
  { name: '서울특별시', gps: '영등포구' },
  { name: '서울특별시', gps: '동작구' },
  { name: '서울특별시', gps: '관악구' },
  { name: '서울특별시', gps: '서초구' },
  { name: '서울특별시', gps: '강남구' },
  { name: '서울특별시', gps: '송파구' },
  { name: '서울특별시', gps: '강동구' },
  { name: '부산광역시', gps: '중구' },
  { name: '부산광역시', gps: '서구' },
  { name: '부산광역시', gps: '동구' },
  { name: '부산광역시', gps: '영도구' },
  { name: '부산광역시', gps: '부산진구' },
  { name: '부산광역시', gps: '동래구' },
  { name: '부산광역시', gps: '남구' },
  { name: '부산광역시', gps: '북구' },
  { name: '부산광역시', gps: '해운대구' },
  { name: '부산광역시', gps: '사하구' },
  { name: '부산광역시', gps: '금정구' },
  { name: '부산광역시', gps: '강서구' },
  { name: '부산광역시', gps: '연제구' },
  { name: '부산광역시', gps: '수영구' },
  { name: '부산광역시', gps: '사상구' },
  { name: '부산광역시', gps: '기장군' },
  { name: '대구광역시', gps: '중구' },
  { name: '대구광역시', gps: '동구' },
  { name: '대구광역시', gps: '서구' },
  { name: '대구광역시', gps: '남구' },
  { name: '대구광역시', gps: '북구' },
  { name: '대구광역시', gps: '수성구' },
  { name: '대구광역시', gps: '달서구' },
  { name: '대구광역시', gps: '달성군' },
  { name: '인천광역시', gps: '중구' },
  { name: '인천광역시', gps: '동구' },
  { name: '인천광역시', gps: '미추홀구' },
  { name: '인천광역시', gps: '연수구' },
  { name: '인천광역시', gps: '남동구' },
  { name: '인천광역시', gps: '부평구' },
  { name: '인천광역시', gps: '계양구' },
  { name: '인천광역시', gps: '서구' },
  { name: '인천광역시', gps: '강화군' },
  { name: '인천광역시', gps: '옹진군' },
  { name: '광주광역시', gps: '동구' },
  { name: '광주광역시', gps: '서구' },
  { name: '광주광역시', gps: '남구' },
  { name: '광주광역시', gps: '북구' },
  { name: '광주광역시', gps: '광산구' },
  { name: '대전광역시', gps: '동구' },
  { name: '대전광역시', gps: '중구' },
  { name: '대전광역시', gps: '서구' },
  { name: '대전광역시', gps: '유성구' },
  { name: '대전광역시', gps: '대덕구' },
  { name: '울산광역시', gps: '중구' },
  { name: '울산광역시', gps: '남구' },
  { name: '울산광역시', gps: '동구' },
  { name: '울산광역시', gps: '북구' },
  { name: '울산광역시', gps: '울주군' },
  { name: '세종특별자치시', gps: '세종특별자치시' },
  { name: '경기도', gps: '수원시' },
  { name: '경기도', gps: '성남시' },
  { name: '경기도', gps: '고양시' },
  { name: '경기도', gps: '용인시' },
  { name: '경기도', gps: '부천시' },
  { name: '경기도', gps: '안산시' },
  { name: '경기도', gps: '안양시' },
  { name: '경기도', gps: '남양주시' },
  { name: '경기도', gps: '화성시' },
  { name: '경기도', gps: '평택시' },
  { name: '경기도', gps: '의정부시' },
  { name: '경기도', gps: '시흥시' },
  { name: '경기도', gps: '파주시' },
  { name: '경기도', gps: '광명시' },
  { name: '경기도', gps: '김포시' },
  { name: '경기도', gps: '군포시' },
  { name: '경기도', gps: '광주시' },
  { name: '경기도', gps: '이천시' },
  { name: '경기도', gps: '양주시' },
  { name: '경기도', gps: '오산시' },
  { name: '경기도', gps: '구리시' },
  { name: '경기도', gps: '안성시' },
  { name: '경기도', gps: '포천시' },
  { name: '경기도', gps: '의왕시' },
  { name: '경기도', gps: '여주시' },
  { name: '경기도', gps: '양평군' },
  { name: '경기도', gps: '동두천시' },
  { name: '경기도', gps: '과천시' },
  { name: '경기도', gps: '가평군' },
  { name: '경기도', gps: '연천군' },
  { name: '강원도', gps: '춘천시' },
  { name: '강원도', gps: '원주시' },
  { name: '강원도', gps: '강릉시' },
  { name: '강원도', gps: '동해시' },
  { name: '강원도', gps: '태백시' },
  { name: '강원도', gps: '속초시' },
  { name: '강원도', gps: '삼척시' },
  { name: '강원도', gps: '홍천군' },
  { name: '강원도', gps: '횡성군' },
  { name: '강원도', gps: '영월군' },
  { name: '강원도', gps: '평창군' },
  { name: '강원도', gps: '정선군' },
  { name: '강원도', gps: '철원군' },
  { name: '강원도', gps: '화천군' },
  { name: '강원도', gps: '양구군' },
  { name: '강원도', gps: '인제군' },
  { name: '강원도', gps: '고성군' },
  { name: '강원도', gps: '양양군' },
  { name: '충청북도', gps: '청주시' },
  { name: '충청북도', gps: '충주시' },
  { name: '충청북도', gps: '제천시' },
  { name: '충청북도', gps: '보은군' },
  { name: '충청북도', gps: '옥천군' },
  { name: '충청북도', gps: '영동군' },
  { name: '충청북도', gps: '진천군' },
  { name: '충청북도', gps: '괴산군' },
  { name: '충청북도', gps: '음성군' },
  { name: '충청북도', gps: '단양군' },
  { name: '충청북도', gps: '증평군' },
  { name: '충청남도', gps: '천안시' },
  { name: '충청남도', gps: '공주시' },
  { name: '충청남도', gps: '보령시' },
  { name: '충청남도', gps: '아산시' },
  { name: '충청남도', gps: '서산시' },
  { name: '충청남도', gps: '논산시' },
  { name: '충청남도', gps: '계룡시' },
  { name: '충청남도', gps: '당진시' },
  { name: '충청남도', gps: '금산군' },
  { name: '충청남도', gps: '부여군' },
  { name: '충청남도', gps: '서천군' },
  { name: '충청남도', gps: '청양군' },
  { name: '충청남도', gps: '홍성군' },
  { name: '충청남도', gps: '예산군' },
  { name: '충청남도', gps: '태안군' },
  { name: '전라북도', gps: '전주시' },
  { name: '전라북도', gps: '군산시' },
  { name: '전라북도', gps: '익산시' },
  { name: '전라북도', gps: '정읍시' },
  { name: '전라북도', gps: '남원시' },
  { name: '전라북도', gps: '전주시' },
  { name: '전라북도', gps: '김제시' },
  { name: '전라북도', gps: '완주군' },
  { name: '전라북도', gps: '진안군' },
  { name: '전라북도', gps: '무주군' },
  { name: '전라북도', gps: '장수군' },
  { name: '전라북도', gps: '임실군' },
  { name: '전라북도', gps: '순창군' },
  { name: '전라북도', gps: '고창군' },
  { name: '전라북도', gps: '부안군' },
  { name: '전라남도', gps: '목포시' },
  { name: '전라남도', gps: '여수시' },
  { name: '전라남도', gps: '순천시' },
  { name: '전라남도', gps: '나주시' },
  { name: '전라남도', gps: '광양시' },
  { name: '전라남도', gps: '담양군' },
  { name: '전라남도', gps: '곡성군' },
  { name: '전라남도', gps: '구례군' },
  { name: '전라남도', gps: '고흥군' },
  { name: '전라남도', gps: '보성군' },
  { name: '전라남도', gps: '화순군' },
  { name: '전라남도', gps: '장흥군' },
  { name: '전라남도', gps: '강진군' },
  { name: '전라남도', gps: '해남군' },
  { name: '전라남도', gps: '영암군' },
  { name: '전라남도', gps: '무안군' },
  { name: '전라남도', gps: '함평군' },
  { name: '전라남도', gps: '영광군' },
  { name: '전라남도', gps: '장성군' },
  { name: '전라남도', gps: '완도군' },
  { name: '전라남도', gps: '진도군' },
  { name: '전라남도', gps: '신안군' },
  { name: '경상북도', gps: '포항시' },
  { name: '경상북도', gps: '경주시' },
  { name: '경상북도', gps: '김천시' },
  { name: '경상북도', gps: '안동시' },
  { name: '경상북도', gps: '구미시' },
  { name: '경상북도', gps: '영주시' },
  { name: '경상북도', gps: '영천시' },
  { name: '경상북도', gps: '상주시' },
  { name: '경상북도', gps: '문경시' },
  { name: '경상북도', gps: '경산시' },
  { name: '경상북도', gps: '군위군' },
  { name: '경상북도', gps: '의성군' },
  { name: '경상북도', gps: '청송군' },
  { name: '경상북도', gps: '영양군' },
  { name: '경상북도', gps: '영덕군' },
  { name: '경상북도', gps: '청도군' },
  { name: '경상북도', gps: '고령군' },
  { name: '경상북도', gps: '성주군' },
  { name: '경상북도', gps: '칠곡군' },
  { name: '경상북도', gps: '예천군' },
  { name: '경상북도', gps: '봉화군' },
  { name: '경상북도', gps: '울진군' },
  { name: '경상북도', gps: '울릉군' },
  { name: '경상남도', gps: '창원시' },
  { name: '경상남도', gps: '진주시' },
  { name: '경상남도', gps: '통영시' },
  { name: '경상남도', gps: '사천시' },
  { name: '경상남도', gps: '김해시' },
  { name: '경상남도', gps: '밀양시' },
  { name: '경상남도', gps: '거제시' },
  { name: '경상남도', gps: '양산시' },
  { name: '경상남도', gps: '의령군' },
  { name: '경상남도', gps: '함안군' },
  { name: '경상남도', gps: '창녕군' },
  { name: '경상남도', gps: '고성군' },
  { name: '경상남도', gps: '남해군' },
  { name: '경상남도', gps: '하동군' },
  { name: '경상남도', gps: '산청군' },
  { name: '경상남도', gps: '함양군' },
  { name: '경상남도', gps: '거창군' },
  { name: '경상남도', gps: '합천군' },
  { name: '제주특별자치도', gps: '제주시' },
  { name: '제주특별자치도', gps: '서귀포시  ' },
];
